image: gcc
before_script:
  - apt-get update --yes
  - apt-get install --yes cmake

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON
    - make install
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - ./build/install/bin/test_demo
