# Use docker gcc official image with cmake installed
image: gcc
before_script:
  - apt-get update --yes
  - apt-get install --yes cmake

# Build task
build:
  stage: build

  # Run build
  script:
    - mkdir build
    - cd build
    - cmake .. -DBUILD_TEST=ON
    - make install

  # Keep built binaries (expire in 1 day)
  artifacts:
    paths:
      - build/
    expire_in: 1 day

# Test task
test:
  stage: test

  # Run test
  script:
    - ./build/install/bin/test_demo
